version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: dataforge-minio
    ports:
      - "9000:9000" # Porta da API S3
      - "9001:9001" # Porta do Painel Web (Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_storage:/data

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/bronze --ignore-existing;
      /usr/bin/mc mb myminio/silver --ignore-existing;
      /usr/bin/mc mb myminio/gold --ignore-existing;
      /usr/bin/mc mb myminio/quarantine --ignore-existing;
      exit 0;
      "

  postgres:
    image: postgres:15
    container_name: dataforge-postgres
    ports:
      - "5433:5432" # Porta mapeada no Mac (5433 para evitar conflito com 5432)
    environment:
      POSTGRES_DB: dataforge_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_storage:
  postgres_data:
